export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";

export const GET_COURSE_DETAILS_FETCH = "GET_COURSE_DETAILS_FETCH";
export const GET_COURSE_DETAILS_SUCCESS = "GET_COURSE_DETAILS_SUCCESS";
export const GET_COURSE_DETAILS_ERROR = "GET_COURSE_DETAILS_ERROR";

export const COURSE_SIGN_UP = "COURSE_SIGN_UP";
export const CREATE_COURSE = "CREATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const CHANGE_COURSE = "CHANGE_COURSE";

export const GET_COURSES_LIST_FETCH = "GET_COURSES_LIST_FETCH";
export const GET_COURSES_LIST_SUCCESS = "GET_COURSES_LIST_SUCCESS";
export const GET_COURSES_LIST_ERROR = "GET_COURSES_LIST_ERROR";

export const GET_GROUPS_FETCH = "GET_GROUPS_FETCH"
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_ERROR = "GET_GROUPS_ERROR";
export const CREATE_GROUP = "CREATE_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

export const GET_USERS = "GET_USERS";
export const GET_ROLES = "GET_ROLES";

